AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template for creating Cloud Resume Challenge resources

Parameters:
  S3BucketName:
    Default: skyscanner-sandbox-eqcloudresume
    Description: s3 bucket name for static website
    Type: String

Resources:
  eqS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Ref S3BucketName 
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False
      WebsiteConfiguration:
        IndexDocument: eqresume.html

  eqS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: 'PublicReadGetObject'
            Effect: Allow
            Principal: '*'
            Action: 
              - 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
          - Effect: Allow
            Principal: 
              # AWS: [REMOVED PRINCIPAL SVC USER FOR PUBLIC REPO]
            Action:
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:AbortMultipartUpload'
              - 's3:List*'
              - 's3:Get*'
            Resource:
              - !Sub 'arn:aws:s3:::${S3BucketName}/*'
              - !Sub 'arn:aws:s3:::${S3BucketName}'

  eqRoute53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      # HostedZoneId: [REMOVED HOSTED ZONE ID FOR PUBLIC REPO]
      Name: eqcloudresume.skyscannerlabs.net
      Type: A
      AliasTarget:
        DNSName: !GetAtt eqCloudFrontDistribution.DomainName
        # HostedZoneId: [REMOVED HOSTED ZONE ID FOR PUBLIC REPO]
            
  eqCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: 
          - eqcloudresume.skyscannerlabs.net
        Enabled: true
        IPV6Enabled: false
        Origins:
          - DomainName: !Select [1, !Split ["//", !GetAtt eqS3Bucket.WebsiteURL]] 
            Id: !GetAtt eqS3Bucket.RegionalDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: !GetAtt eqS3Bucket.RegionalDomainName
          ViewerProtocolPolicy: redirect-to-https
          # CachePolicyId: [REMOVED CACHE POLICY ID FOR PUBLIC REPO]
        ViewerCertificate:
          # AcmCertificateArn: [REMOVED CERTIFICATE ARN FOR PUBLIC REPO]
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only


  eqDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: eq-visitorcounter
      AttributeDefinitions:
        - AttributeName: visitor-info
          AttributeType: S
      KeySchema:
        - AttributeName: visitor-info
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  